### PR TITLE
Title Scene

### PR DESCRIPTION
**Pull request by Reedric**
Modeled title scene in game

### CODE REVIEW

**Comment by keptsecret** [comment]
Seems to be superseded by #66, so I'm closing this. Can reopen otherwise.

**Comment by kevinsadi** [comment]
wait sorry, the content of the TitleScene's seem to be different, but Avery's changes just include the fish, I will resolve this as I merge

**Comment by kevinsadi** [comment]
This PR is giving me linking errors. Let me see what I can do about it 😢 

image

**Comment by kevinsadi** [comment]
added this in PR #67

**Pull request closed without merging**
