### PR TITLE
Fishy Go Fly

### PR DESCRIPTION
**Pull request by averylg**
Adds flying fish in SceneTitle (not a title screen yet so kinda misleading)
Features:
- Fish flies around the center of the map in a circle.

### CODE REVIEW

**Comment by keptsecret** [comment]
What's the difference between this and #65?

**Comment by kevinsadi** [comment]
> What's the difference between this and #65?

This is building on #65 it seems, it just added a fish that flies around the screen 

```
		// Fly fishy fly!
		m_fishTheta -= m_deltaTheta;
		Entity* fishObj = GetEntity("Fish");
		fishObj->SetPosition(glm::vec3(
			m_fishRadius * glm::cos(m_fishTheta),
			85.0f,
			m_fishRadius * glm::sin(m_fishTheta)
		));
		fishObj->SetYawRotation(m_fishTheta * -360.0f / (2.0f * glm::pi<float>()));
		```

**Comment by keptsecret** [comment]
Safe to close #65 then...

**Review by kevinsadi — APPROVED** [review]
prettyy coooolll, another PR would be cool that includes like a whole school of fish moving together

**Pull request merged**
